import { type Wallet } from "./types";
import { type currencyCodes } from "./types";

export const AppWallet: Wallet[] = [
    {
        code: "AFN",
        name: "Afghan Afghani",
        amount: 30000,
        totalSpend: 100,
    },
    {
        code: "ALL",
        name: "Albanian Lek",
        amount: 12,
        totalSpend: 80,
    },
    {
        code: "AMD",
        name: "Armenian Dram",
        amount: 1000,
        totalSpend: 290,
    },
    {
        amount: 1200,
        code: "RUB",
        name: "Russian Ruble",
        totalSpend: 11.99,
    }
]

export const supportedCodes: currencyCodes[] = [
  ["AED","UAE Dirham"],
  ["AFN","Afghan Afghani"],
  ["ALL","Albanian Lek"],
  ["AMD","Armenian Dram"],
  ["ANG","Netherlands Antillian Guilder"],
  ["AOA","Angolan Kwanza"],
  ["ARS","Argentine Peso"],
  ["AUD","Australian Dollar"],
  ["AWG","Aruban Florin"],
  ["AZN","Azerbaijani Manat"],
  ["BAM","Bosnia and Herzegovina Convertible Mark"],
  ["BBD","Barbados Dollar"],
  ["BDT","Bangladeshi Taka"],
  ["BGN","Bulgarian Lev"],
  ["BHD","Bahraini Dinar"],
  ["BIF","Burundian Franc"],
  ["BMD","Bermudian Dollar"],
  ["BND","Brunei Dollar"],
  ["BOB","Bolivian Boliviano"],
  ["BRL","Brazilian Real"],
  ["BSD","Bahamian Dollar"],
  ["BTN","Bhutanese Ngultrum"],
  ["BWP","Botswana Pula"],
  ["BYN","Belarusian Ruble"],
  ["BZD","Belize Dollar"],
  ["CAD","Canadian Dollar"],
  ["CDF","Congolese Franc"],
  ["CHF","Swiss Franc"],
  ["CLF","Chilean Unidad de Fomento"],
  ["CLP","Chilean Peso"],
  ["CNH","Offshore Chinese Renminbi"],
  ["CNY","Chinese Renminbi"],
  ["COP","Colombian Peso"],
  ["CRC","Costa Rican Colon"],
  ["CUP","Cuban Peso"],
  ["CVE","Cape Verdean Escudo"],
  ["CZK","Czech Koruna"],
  ["DJF","Djiboutian Franc"],
  ["DKK","Danish Krone"],
  ["DOP","Dominican Peso"],
  ["DZD","Algerian Dinar"],
  ["EGP","Egyptian Pound"],
  ["ERN","Eritrean Nakfa"],
  ["ETB","Ethiopian Birr"],
  ["EUR","Euro"],
  ["FJD","Fiji Dollar"],
  ["FKP","Falkland Islands Pound"],
  ["FOK","Faroese Króna"],
  ["GBP","Pound Sterling"],
  ["GEL","Georgian Lari"],
  ["GGP","Guernsey Pound"],
  ["GHS","Ghanaian Cedi"],
  ["GIP","Gibraltar Pound"],
  ["GMD","Gambian Dalasi"],
  ["GNF","Guinean Franc"],
  ["GTQ","Guatemalan Quetzal"],
  ["GYD","Guyanese Dollar"],
  ["HKD","Hong Kong Dollar"],
  ["HNL","Honduran Lempira"],
  ["HRK","Croatian Kuna"],
  ["HTG","Haitian Gourde"],
  ["HUF","Hungarian Forint"],
  ["IDR","Indonesian Rupiah"],
  ["ILS","Israeli New Shekel"],
  ["IMP","Manx Pound"],
  ["INR","Indian Rupee"],
  ["IQD","Iraqi Dinar"],
  ["IRR","Iranian Rial"],
  ["ISK","Icelandic Króna"],
  ["JEP","Jersey Pound"],
  ["JMD","Jamaican Dollar"],
  ["JOD","Jordanian Dinar"],
  ["JPY","Japanese Yen"],
  ["KES","Kenyan Shilling"],
  ["KGS","Kyrgyzstani Som"],
  ["KHR","Cambodian Riel"],
  ["KID","Kiribati Dollar"],
  ["KMF","Comorian Franc"],
  ["KRW","South Korean Won"],
  ["KWD","Kuwaiti Dinar"],
  ["KYD","Cayman Islands Dollar"],
  ["KZT","Kazakhstani Tenge"],
  ["LAK","Lao Kip"],
  ["LBP","Lebanese Pound"],
  ["LKR","Sri Lanka Rupee"],
  ["LRD","Liberian Dollar"],
  ["LSL","Lesotho Loti"],
  ["LYD","Libyan Dinar"],
  ["MAD","Moroccan Dirham"],
  ["MDL","Moldovan Leu"],
  ["MGA","Malagasy Ariary"],
  ["MKD","Macedonian Denar"],
  ["MMK","Burmese Kyat"],
  ["MNT","Mongolian Tögrög"],
  ["MOP","Macanese Pataca"],
  ["MRU","Mauritanian Ouguiya"],
  ["MUR","Mauritian Rupee"],
  ["MVR","Maldivian Rufiyaa"],
  ["MWK","Malawian Kwacha"],
  ["MXN","Mexican Peso"],
  ["MYR","Malaysian Ringgit"],
  ["MZN","Mozambican Metical"],
  ["NAD","Namibian Dollar"],
  ["NGN","Nigerian Naira"],
  ["NIO","Nicaraguan Córdoba"],
  ["NOK","Norwegian Krone"],
  ["NPR","Nepalese Rupee"],
  ["NZD","New Zealand Dollar"],
  ["OMR","Omani Rial"],
  ["PAB","Panamanian Balboa"],
  ["PEN","Peruvian Sol"],
  ["PGK","Papua New Guinean Kina"],
  ["PHP","Philippine Peso"],
  ["PKR","Pakistani Rupee"],
  ["PLN","Polish Złoty"],
  ["PYG","Paraguayan Guaraní"],
  ["QAR","Qatari Riyal"],
  ["RON","Romanian Leu"],
  ["RSD","Serbian Dinar"],
  ["RUB","Russian Ruble"],
  ["RWF","Rwandan Franc"],
  ["SAR","Saudi Riyal"],
  ["SBD","Solomon Islands Dollar"],
  ["SCR","Seychellois Rupee"],
  ["SDG","Sudanese Pound"],
  ["SEK","Swedish Krona"],
  ["SGD","Singapore Dollar"],
  ["SHP","Saint Helena Pound"],
  ["SLE","Sierra Leonean Leone"],
  ["SLL","Sierra Leonean Leone"],
  ["SOS","Somali Shilling"],
  ["SRD","Surinamese Dollar"],
  ["SSP","South Sudanese Pound"],
  ["STN","São Tomé and Príncipe Dobra"],
  ["SYP","Syrian Pound"],
  ["SZL","Eswatini Lilangeni"],
  ["THB","Thai Baht"],
  ["TJS","Tajikistani Somoni"],
  ["TMT","Turkmenistan Manat"],
  ["TND","Tunisian Dinar"],
  ["TOP","Tongan Paʻanga"],
  ["TRY","Turkish Lira"],
  ["TTD","Trinidad and Tobago Dollar"],
  ["TVD","Tuvaluan Dollar"],
  ["TWD","New Taiwan Dollar"],
  ["TZS","Tanzanian Shilling"],
  ["UAH","Ukrainian Hryvnia"],
  ["UGX","Ugandan Shilling"],
  ["USD","United States Dollar"],
  ["UYU","Uruguayan Peso"],
  ["UZS","Uzbekistani So'm"],
  ["VES","Venezuelan Bolívar Soberano"],
  ["VND","Vietnamese Đồng"],
  ["VUV","Vanuatu Vatu"],
  ["WST","Samoan Tālā"],
  ["XAF","Central African CFA Franc"],
  ["XCD","East Caribbean Dollar"],
  ["XCG","Caribbean Guilder"],
  ["XDR","Special Drawing Rights"],
  ["XOF","West African CFA franc"],
  ["XPF","CFP Franc"],
  ["YER","Yemeni Rial"],
  ["ZAR","South African Rand"],
  ["ZMW","Zambian Kwacha"],
  ["ZWL","Zimbabwean Dollar"]
]

export const codeCurrency = [
  { code: 'AED', currency: 'UAE Dirham', country: 'United Arab Emirates' },
  { code: 'AFN', currency: 'Afghan Afghani', country: 'Afghanistan' },
  { code: 'ALL', currency: 'Albanian Lek', country: 'Albania' },
  { code: 'AMD', currency: 'Armenian Dram', country: 'Armenia' },
  { code: 'ANG', currency: 'Netherlands Antillian Guilder', country: 'Netherlands Antilles' },
  { code: 'AOA', currency: 'Angolan Kwanza', country: 'Angola' },
  { code: 'ARS', currency: 'Argentine Peso', country: 'Argentina' },
  { code: 'AUD', currency: 'Australian Dollar', country: 'Australia' },
  { code: 'AWG', currency: 'Aruban Florin', country: 'Aruba' },
  { code: 'AZN', currency: 'Azerbaijani Manat', country: 'Azerbaijan' },
  { code: 'BAM', currency: 'Bosnia and Herzegovina Mark', country: 'Bosnia and Herzegovina' },
  { code: 'BBD', currency: 'Barbados Dollar', country: 'Barbados' },
  { code: 'BDT', currency: 'Bangladeshi Taka', country: 'Bangladesh' },
  { code: 'BGN', currency: 'Bulgarian Lev', country: 'Bulgaria' },
  { code: 'BHD', currency: 'Bahraini Dinar', country: 'Bahrain' },
  { code: 'BIF', currency: 'Burundian Franc', country: 'Burundi' },
  { code: 'BMD', currency: 'Bermudian Dollar', country: 'Bermuda' },
  { code: 'BND', currency: 'Brunei Dollar', country: 'Brunei' },
  { code: 'BOB', currency: 'Bolivian Boliviano', country: 'Bolivia' },
  { code: 'BRL', currency: 'Brazilian Real', country: 'Brazil' },
  { code: 'BSD', currency: 'Bahamian Dollar', country: 'Bahamas' },
  { code: 'BTN', currency: 'Bhutanese Ngultrum', country: 'Bhutan' },
  { code: 'BWP', currency: 'Botswana Pula', country: 'Botswana' },
  { code: 'BYN', currency: 'Belarusian Ruble', country: 'Belarus' },
  { code: 'BZD', currency: 'Belize Dollar', country: 'Belize' },
  { code: 'CAD', currency: 'Canadian Dollar', country: 'Canada' },
  { code: 'CDF', currency: 'Congolese Franc', country: 'Democratic Republic of the Congo' },
  { code: 'CHF', currency: 'Swiss Franc', country: 'Switzerland' },
  { code: 'CLP', currency: 'Chilean Peso', country: 'Chile' },
  { code: 'CNY', currency: 'Chinese Renminbi', country: 'China' },
  { code: 'COP', currency: 'Colombian Peso', country: 'Colombia' },
  { code: 'CRC', currency: 'Costa Rican Colon', country: 'Costa Rica' },
  { code: 'CUP', currency: 'Cuban Peso', country: 'Cuba' },
  { code: 'CVE', currency: 'Cape Verdean Escudo', country: 'Cape Verde' },
  { code: 'CZK', currency: 'Czech Koruna', country: 'Czech Republic' },
  { code: 'DJF', currency: 'Djiboutian Franc', country: 'Dijibouti' },
  { code: 'DKK', currency: 'Danish Krone', country: 'Denmark' },
  { code: 'DOP', currency: 'Dominican Peso', country: 'Dominican Republic' },
  { code: 'DZD', currency: 'Algerian Dinar', country: 'Algeria' },
  { code: 'EGP', currency: 'Egyptian Pound', country: 'Egypt' },
  { code: 'ERN', currency: 'Eritrean Nakfa', country: 'Eritrea' },
  { code: 'ETB', currency: 'Ethiopian Birr', country: 'Ethiopia' },
  { code: 'EUR', currency: 'Euro', country: 'European Union' },
  { code: 'FJD', currency: 'Fiji Dollar', country: 'Fiji' },
  { code: 'FKP', currency: 'Falkland Islands Pound', country: 'Falkland Islands' },
  { code: 'FOK', currency: 'Faroese Króna', country: 'Faroe Islands' },
  { code: 'GBP', currency: 'Pound Sterling', country: 'United Kingdom' },
  { code: 'GEL', currency: 'Georgian Lari', country: 'Georgia' },
  { code: 'GGP', currency: 'Guernsey Pound', country: 'Guernsey' },
  { code: 'GHS', currency: 'Ghanaian Cedi', country: 'Ghana' },
  { code: 'GIP', currency: 'Gibraltar Pound', country: 'Gibraltar' },
  { code: 'GMD', currency: 'Gambian Dalasi', country: 'The Gambia' },
  { code: 'GNF', currency: 'Guinean Franc', country: 'Guinea' },
  { code: 'GTQ', currency: 'Guatemalan Quetzal', country: 'Guatemala' },
  { code: 'GYD', currency: 'Guyanese Dollar', country: 'Guyana' },
  { code: 'HKD', currency: 'Hong Kong Dollar', country: 'Hong Kong' },
  { code: 'HNL', currency: 'Honduran Lempira', country: 'Honduras' },
  { code: 'HRK', currency: 'Croatian Kuna', country: 'Croatia' },
  { code: 'HTG', currency: 'Haitian Gourde', country: 'Haiti' },
  { code: 'HUF', currency: 'Hungarian Forint', country: 'Hungary' },
  { code: 'IDR', currency: 'Indonesian Rupiah', country: 'Indonesia' },
  { code: 'ILS', currency: 'Israeli New Shekel', country: 'Israel' },
  { code: 'IMP', currency: 'Manx Pound', country: 'Isle of Man' },
  { code: 'INR', currency: 'Indian Rupee', country: 'India' },
  { code: 'IQD', currency: 'Iraqi Dinar', country: 'Iraq' },
  { code: 'IRR', currency: 'Iranian Rial', country: 'Iran' },
  { code: 'ISK', currency: 'Icelandic Króna', country: 'Iceland' },
  { code: 'JEP', currency: 'Jersey Pound', country: 'Jersey' },
  { code: 'JMD', currency: 'Jamaican Dollar', country: 'Jamaica' },
  { code: 'JOD', currency: 'Jordanian Dinar', country: 'Jordan' },
  { code: 'JPY', currency: 'Japanese Yen', country: 'Japan' },
  { code: 'KES', currency: 'Kenyan Shilling', country: 'Kenya' },
  { code: 'KGS', currency: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
  { code: 'KHR', currency: 'Cambodian Riel', country: 'Cambodia' },
  { code: 'KID', currency: 'Kiribati Dollar', country: 'Kiribati' },
  { code: 'KMF', currency: 'Comorian Franc', country: 'Comoros' },
  { code: 'KRW', currency: 'South Korean Won', country: 'South Korea' },
  { code: 'KWD', currency: 'Kuwaiti Dinar', country: 'Kuwait' },
  { code: 'KYD', currency: 'Cayman Islands Dollar', country: 'Cayman Islands' },
  { code: 'KZT', currency: 'Kazakhstani Tenge', country: 'Kazakhstan' },
  { code: 'LAK', currency: 'Lao Kip', country: 'Laos' },
  { code: 'LBP', currency: 'Lebanese Pound', country: 'Lebanon' },
  { code: 'LKR', currency: 'Sri Lanka Rupee', country: 'Sri Lanka' },
  { code: 'LRD', currency: 'Liberian Dollar', country: 'Liberia' },
  { code: 'LSL', currency: 'Lesotho Loti', country: 'Lesotho' },
  { code: 'LYD', currency: 'Libyan Dinar', country: 'Libya' },
  { code: 'MAD', currency: 'Moroccan Dirham', country: 'Morocco' },
  { code: 'MDL', currency: 'Moldovan Leu', country: 'Moldova' },
  { code: 'MGA', currency: 'Malagasy Ariary', country: 'Madagascar' },
  { code: 'MKD', currency: 'Macedonian Denar', country: 'North Macedonia' },
  { code: 'MMK', currency: 'Burmese Kyat', country: 'Myanmar' },
  { code: 'MNT', currency: 'Mongolian Tögrög', country: 'Mongolia' },
  { code: 'MOP', currency: 'Macanese Pataca', country: 'Macau' },
  { code: 'MRU', currency: 'Mauritanian Ouguiya', country: 'Mauritania' },
  { code: 'MUR', currency: 'Mauritian Rupee', country: 'Mauritius' },
  { code: 'MVR', currency: 'Maldivian Rufiyaa', country: 'Maldives' },
  { code: 'MWK', currency: 'Malawian Kwacha', country: 'Malawi' },
  { code: 'MXN', currency: 'Mexican Peso', country: 'Mexico' },
  { code: 'MYR', currency: 'Malaysian Ringgit', country: 'Malaysia' },
  { code: 'MZN', currency: 'Mozambican Metical', country: 'Mozambique' },
  { code: 'NAD', currency: 'Namibian Dollar', country: 'Namibia' },
  { code: 'NGN', currency: 'Nigerian Naira', country: 'Nigeria' },
  { code: 'NIO', currency: 'Nicaraguan Córdoba', country: 'Nicaragua' },
  { code: 'NOK', currency: 'Norwegian Krone', country: 'Norway' },
  { code: 'NPR', currency: 'Nepalese Rupee', country: 'Nepal' },
  { code: 'NZD', currency: 'New Zealand Dollar', country: 'New Zealand' },
  { code: 'OMR', currency: 'Omani Rial', country: 'Oman' },
  { code: 'PAB', currency: 'Panamanian Balboa', country: 'Panama' },
  { code: 'PEN', currency: 'Peruvian Sol', country: 'Peru' },
  { code: 'PGK', currency: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
  { code: 'PHP', currency: 'Philippine Peso', country: 'Philippines' },
  { code: 'PKR', currency: 'Pakistani Rupee', country: 'Pakistan' },
  { code: 'PLN', currency: 'Polish Złoty', country: 'Poland' },
  { code: 'PYG', currency: 'Paraguayan Guaraní', country: 'Paraguay' },
  { code: 'QAR', currency: 'Qatari Riyal', country: 'Qatar' },
  { code: 'RON', currency: 'Romanian Leu', country: 'Romania' },
  { code: 'RSD', currency: 'Serbian Dinar', country: 'Serbia' },
  { code: 'RUB', currency: 'Russian Ruble', country: 'Russia' },
  { code: 'RWF', currency: 'Rwandan Franc', country: 'Rwanda' },
  { code: 'SAR', currency: 'Saudi Riyal', country: 'Saudi Arabia' },
  { code: 'SBD', currency: 'Solomon Islands Dollar', country: 'Solomon Islands' },
  { code: 'SCR', currency: 'Seychellois Rupee', country: 'Seychelles' },
  { code: 'SDG', currency: 'Sudanese Pound', country: 'Sudan' },
  { code: 'SEK', currency: 'Swedish Krona', country: 'Sweden' },
  { code: 'SGD', currency: 'Singapore Dollar', country: 'Singapore' },
  { code: 'SHP', currency: 'Saint Helena Pound', country: 'Saint Helena' },
  { code: 'SLE', currency: 'Sierra Leonean Leone', country: 'Sierra Leone' },
  { code: 'SOS', currency: 'Somali Shilling', country: 'Somalia' },
  { code: 'SRD', currency: 'Surinamese Dollar', country: 'Suriname' },
  { code: 'SSP', currency: 'South Sudanese Pound', country: 'South Sudan' },
  { code: 'STN', currency: 'São Tomé and Príncipe Dobra', country: 'São Tomé and Príncipe' },
  { code: 'SYP', currency: 'Syrian Pound', country: 'Syria' },
  { code: 'SZL', currency: 'Eswatini Lilangeni', country: 'Eswatini' },
  { code: 'THB', currency: 'Thai Baht', country: 'Thailand' },
  { code: 'TJS', currency: 'Tajikistani Somoni', country: 'Tajikistan' },
  { code: 'TMT', currency: 'Turkmenistan Manat', country: 'Turkmenistan' },
  { code: 'TND', currency: 'Tunisian Dinar', country: 'Tunisia' },
  { code: 'TOP', currency: 'Tongan Paʻanga', country: 'Tonga' },
  { code: 'TRY', currency: 'Turkish Lira', country: 'Turkey' },
  { code: 'TTD', currency: 'Trinidad and Tobago Dollar', country: 'Trinidad and Tobago' },
  { code: 'TVD', currency: 'Tuvaluan Dollar', country: 'Tuvalu' },
  { code: 'TWD', currency: 'New Taiwan Dollar', country: 'Taiwan' },
  { code: 'TZS', currency: 'Tanzanian Shilling', country: 'Tanzania' },
  { code: 'UAH', currency: 'Ukrainian Hryvnia', country: 'Ukraine' },
  { code: 'UGX', currency: 'Ugandan Shilling', country: 'Uganda' },
  { code: 'USD', currency: 'United States Dollar', country: 'United States' },
  { code: 'UYU', currency: 'Uruguayan Peso', country: 'Uruguay' },
  { code: 'UZS', currency: 'Uzbekistani So\'m', country: 'Uzbekistan' },
  { code: 'VES', currency: 'Venezuelan Bolívar Soberano', country: 'Venezuela' },
  { code: 'VND', currency: 'Vietnamese Đồng', country: 'Vietnam' },
  { code: 'VUV', currency: 'Vanuatu Vatu', country: 'Vanuatu' },
  { code: 'WST', currency: 'Samoan Tālā', country: 'Samoa' },
  { code: 'XAF', currency: 'Central African CFA Franc', country: 'CEMAC' },
  { code: 'XCD', currency: 'East Caribbean Dollar', country: 'Organisation of Eastern Caribbean States' },
  { code: 'XDR', currency: 'Special Drawing Rights', country: 'International Monetary Fund' },
  { code: 'XOF', currency: 'West African CFA franc', country: 'CFA' },
  { code: 'XPF', currency: 'CFP Franc', country: 'Collectivités d\'Outre-Mer' },
  { code: 'YER', currency: 'Yemeni Rial', country: 'Yemen' },
  { code: 'ZAR', currency: 'South African Rand', country: 'South Africa' },
  { code: 'ZMW', currency: 'Zambian Kwacha', country: 'Zambia' },
  { code: 'ZWL', currency: 'Zimbabwean Dollar', country: 'Zimbabwe' }
];


export const  Currency = {
AED: 3.6725,
AFN: 67.627,
ALL: 82.8887,
AMD: 382.8609,
ANG: 1.79,
AOA: 918.9429,
ARS: 1332,
AUD: 1.5273,
AWG: 1.79,
AZN: 1.7006,
BAM: 1.6714,
BBD: 2,
BDT: 121.8352,
BGN: 1.6714,
BHD: 0.376,
BIF: 2939.8587,
BMD: 1,
BND: 1.2922,
BOB: 6.9192,
BRL: 5.3534,
BSD: 1,
BTN: 88.752,
BWP: 13.5789,
BYN: 3.3554,
BZD: 2,
CAD: 1.3939,
CDF: 2751.6696,
CHF: 0.7978,
CLP: 959.5035,
CNY: 7.1407,
COP: 3905.801,
CRC: 504.7776,
CUP: 24,
CVE: 94.2278,
CZK: 20.7746,
DJF: 177.721,
DKK: 6.3759,
DOP: 62.2667,
DZD: 129.6644,
EGP: 48.1369,
ERN: 15,
ETB: 143.8415,
EUR: 0.8545,
FJD: 2.2587,
FKP: 0.7462,
FOK: 6.3763,
GBP: 0.7462,
GEL: 2.707,
GGP: 0.7462,
GHS: 12.3475,
GIP: 0.7462,
GMD: 73.3932,
GNF: 8708.5352,
GTQ: 7.6661,
GYD: 209.2377,
HKD: 7.7806,
HNL: 26.2709,
HRK: 6.4387,
HTG: 130.8872,
HUF: 334.5659,
IDR: 16720.5289,
ILS: 3.3445,
IMP: 0.7462,
INR: 88.7521,
IQD: 1309.384,
IRR: 43101.4459,
ISK: 121.6463,
JEP: 0.7462,
JMD: 160.4389,
JOD: 0.709,
JPY: 149.4533,
KES: 129.2421,
KGS: 87.4273,
KHR: 4013.7069,
KID: 1.5274,
KMF: 420.4148,
KRW: 1409.3444,
KWD: 0.3056,
KYD: 0.8333,
KZT: 544.7154,
LAK: 21790.8328,
LBP: 89500,
LKR: 302.3893,
LRD: 181.3629,
LSL: 17.368,
LYD: 5.407,
MAD: 9.101,
MDL: 16.6954,
MGA: 4431.0988,
MKD: 52.7533,
MMK: 2101.6124,
MNT: 3612.1737,
MOP: 8.0137,
MRU: 39.9796,
MUR: 45.7532,
MVR: 15.4259,
MWK: 1735.932,
MXN: 18.3793,
MYR: 4.2213,
MZN: 63.7742,
NAD: 17.368,
NGN: 1485.4747,
NIO: 36.8438,
NOK: 9.9758,
NPR: 142.0031,
NZD: 1.7316,
OMR: 0.3845,
PAB: 1,
PEN: 3.5062,
PGK: 4.1808,
PHP: 58.1883,
PKR: 283.14,
PLN: 3.6478,
PYG: 7118.8875,
QAR: 3.64,
RON: 4.3504,
RSD: 100.3215,
RUB: 83.4143,
RWF: 1452.4209,
SAR: 3.75,
SBD: 8.2235,
SCR: 14.867,
SDG: 458.7838,
SEK: 9.411,
SGD: 1.2922,
SHP: 0.7462,
SLE: 23.268,
SLL: 23268.0286,
SOS: 571.3119,
SRD: 37.8722,
SSP: 4674.2136,
STN: 20.9367,
SYP: 12905.8995,
SZL: 17.368,
THB: 32.2442,
TJS: 9.4087,
TMT: 3.4989,
TND: 2.9187,
TOP: 2.3633,
TRY: 41.5893,
TTD: 6.7883,
TVD: 1.5274,
TWD: 30.4462,
TZS: 2453.0911,
UAH: 41.4831,
UGX: 3524.2307,
USD: 1,
UYU: 39.9024,
UZS: 12188.11,
VES: 175.6471,
VND: 26307.1354,
VUV: 119.9897,
WST: 2.7217,
XAF: 560.553,
XCD: 2.7,
XCG: 1.79,
XDR: 0.732,
XOF: 560.553,
XPF: 101.9761,
YER: 239.3572,
ZAR: 17.3654,
ZMW: 23.7882,
ZWL: 26.5708,
}

